### ISSUE TITLE
Adding "Weight" to the attributes list

### ISSUE THREAD

**Issue by katywebster** [nolastan/sync.sketchplugin#1]
Hi there,

Would it be possible to add the "Weight" of the font to your list of attributes? I use this in my text styles for bold/semi-bold/light versions of the font.

Many thanks,

Katy

**Comment by nolastan** [comment]
As you can see from the [template doc](https://drive.google.com/previewtemplate?id=17q6GOMM1X6kkvgeL3LeGkRr4C2vOhpM_JiQUWxbBtew&mode=public), you can specify weight and other variants in the typeface column. Make sure to specify the variant exactly as the font is named in your Mac's font folder.

**Comment by nolastan** [comment]
To elaborate a bit more – I don't know how to implement that as a column because fonts have different naming conventions. Maybe if I dig into how Mac handles fonts a little more I could figure something out.
