### ISSUE TITLE
Sync with API generated from Google Spreadsheet not workin

### ISSUE THREAD

**Issue by rgesulfo** [nolastan/sync.sketchplugin#11]
Hi,

Very nice plugin! Unfortunately, the API generated with the tool you mention doesn't work for me. I pasted the url generated: https://sheetsu.com/apis/c07cf456 in your plugin's prompt. But nothing seems to change.

Do you have any idea how to do please?

Thank you!

**Comment by n8mills** [comment]
having the same issue

**Comment by nolastan** [comment]
I was able to reproduce the error so I've reverted the most recent update for now and will investigate further. It seems the styles are loading from the default URL even if you change it.
