### ISSUE TITLE
Sync should have an option to PUSH changes to the spreadsheet

### ISSUE THREAD

**Issue by JWhiteUX** [nolastan/sync.sketchplugin#15]
Issue: I just overwrote my existing text styles using sync. It's more intuitive to push styles from a document than to manually enter them after having created them in sketch.

Workflow:
1) New file
2) Mockup designs and create styles
3) Save File
4) Sync > Push to GoogleDoc
- Confirmation dialog "Are you sure?" 
  End

**Comment by nolastan** [comment]
That would be cool but sounds really complicated because Sketch would have to authenticate with your Google account to be able to write to the document. Do you know of any plugins that authenticate with a web service?

**Comment by JWhiteUX** [comment]
Send to Slack
Marvel
Invision
Zeplin

All use an API key/token of some sort

**Comment by JWhiteUX** [comment]
What if Sync created it's own file?

**Comment by shanegriffiths** [comment]
I would love to see this progressed. This is one of our biggest issues with Sketch right now. I think there's a real opportunity to create something of value here (worth paying for).

**Comment by JWhiteUX** [comment]
This proposal should not replace the existing PULL feature, rather, it should extend the capabilities of the Sync plugin.

Thought I would clear that up after rereading my remarks.

**Comment by nolastan** [comment]
[Google Drive auth](https://developers.google.com/drive/v3/web/about-auth) is a bit more complicated than just copy/pasting a token.

Sync generating its own csv would probably be easier, and then that csv could be uploaded to Drive.

It could also be done with [Sheetsu](https://sheetsu.com/).

**Comment by nolastan** [comment]
This will log typography styles in csv format. Then you can import this into Google Drive. Still need to figure out how to get character and and line height, and export as a file.

Output: 

```
Style, Typeface, Color, Opacity, Size, Alignment, Line, Character
My Style 1, SFUIText-Light, #000000, 0.34, 15, left, @TODO, @TODO
My Style 2, SFUIText, #333, 1, 24, right, @TODO, @TODO
etc…
```

Code:

```
log('Style, Typeface, Color, Opacity, Size, Alignment, Line, Character');

var alignmentEnum = Object.freeze([
  'left','right','center','justified'
]);

var doc = context.document;
var sharedStyles = doc.documentData().layerTextStyles();
var styleObjects = sharedStyles.objects();

for (var i=0; i<styleObjects.length; i++) {
  var name = styleObjects[i].name();

  var attributes = styleObjects[i].style().textStyle().attributes()

  var paragraphStyle = attributes.NSParagraphStyle;
  var alignment = alignmentEnum[paragraphStyle.alignment()];

  var line = "@TODO";
  var character = "@TODO";

  var font = attributes.NSFont.fontName();
  var color = '#' + attributes.NSColor.hexValue();
  var opacity = attributes.NSColor.alphaComponent();
  var size = attributes.NSFont.pointSize();

  log(name +', '+ font  +', '+ color +', '+ opacity +', '+ size +', '+ alignment +', '+ line +', '+ character);
}
```

**Comment by nolastan** [comment]
Alright, I figured out the missing features and it appears to be all working. [Check out the branch](https://github.com/nolastan/sync.sketchplugin/tree/export) (you'll need to download and rename the folder to `sync.sketchplugin`, then open it). I'll do some cleanup and then merge it in.

**Comment by nolastan** [comment]
Some feedback here would be great! I've been using the branch myself but somehow others always run into issues I don't ;)
