### ISSUE TITLE
Great alternative to brand.ai

### ISSUE THREAD

**Issue by ebuah** [nolastan/sync.sketchplugin#16]
Didn't know where to send this so feel free to delete it. I found this plugin via link on producthunt @ brand.ai. I love this alternative and hope you keep it up. Happy to help when and where possible.

**Comment by nolastan** [comment]
I really appreciate that! When I saw brand.ai yesterday I wondered if demand for Sync would keep up, so your comment means a lot. I plan to try it out and perhaps focus more on what makes Sync unique.

**Comment by emmanuelbuah** [comment]
I think you have a lot of the pieces. A good change will be to move away from google docs to an api db backed service. With an api service in place,  a UI/style guide editor(in sketch or web or both)  that connects and uses the api service, will complete the integration. Thus Sketch plugin (UI editor/applier) <-> sync api service.

If the sync api service is a application that can be span using a heroku button, then users can just spin up their heroku sync api service instance, add the service url to the sketch sync plugin and you are up and running.

**Comment by nolastan** [comment]
A hosted API would be great! And I think Google Docs should remain as an option because it is often available at large companies that have restrictions on what tools designers can use, and because it's more lightweight than spinning up a heroku instance.
