### ISSUE TITLE
REQ: Palette as part of the document not global

### ISSUE THREAD

**Issue by iamhenry** [nolastan/sync.sketchplugin#18]
Would it be possible to have the plugin override the document colors as opposed to the Global Sketch Palette? 

That would be great. Thanks!

**Comment by KlarityStudio** [comment]
I second this. The plugin replaced all my document colors and I am unable to get them back :(

Would be better if the colors were added to the document palette instead.

**Comment by KlarityStudio** [comment]
I managed to modify the plugin to add the colors to document instead.

script.cocoascript line 29 change to
applyColors(parseSheetsData(data), doc.documentData(), doc);

colors.js line 1 change to
var applyColors = function (newColors, docData, doc) {

colors.js line 11 change to
doc.documentData().assets().setPrimitiveColors(colors);

**Comment by nolastan** [comment]
@KlarityStudio Would you like to [fork](https://github.com/nolastan/sync.sketchplugin/fork) the project, make your edits to these files, and submit a pull request?
