### ISSUE TITLE
Not working on Sketch 3.4.2

### ISSUE THREAD

**Issue by vinishsaini** [nolastan/sync.sketchplugin#2]
I installed it today and followed all instruction. When I run this plugin I can't see new styles in Sketch? Am I missing something? Please help coz this plugin is really cool and our team want to use it asap.

Thanks
Vinish

**Comment by nolastan** [comment]
It's working fine for me in 3.4.2. Are you getting a "Sync Complete!" message at the bottom of the window?

Also note if you have a text field selected, you have to unselect and reselect it to see the new styles.

**Comment by vinishsaini** [comment]
Thanks for reply! I didn't see any message of sync complete. Is it possible if you show some screenshots of how it actually work for you? Thanks!

**Comment by nolastan** [comment]
So I think I found an issue on Friday, mind re-downloading and installing the plugin? I'll work on getting a screencast up.

**Comment by nolastan** [comment]
Screencast now in the readme

**Comment by vinishsaini** [comment]
Thanks Man! Let me try.

**Comment by vinishsaini** [comment]
Hurray!!! Working perfectly! :)
