### ISSUE TITLE
Not working with Sketch 39

### ISSUE THREAD

**Issue by hashcc** [nolastan/sync.sketchplugin#21]
I can't sync styles by removeObject error.
- URL: (default url) https://docs.google.com/spreadsheets/d/17q6GOMM1X6kkvgeL3LeGkRr4C2vOhpM_JiQUWxbBtew/pubhtml
- Version: Version 39.1 (31720)

```
2016/07/26 14:18:04.625 Sync (Sketch Plugin)[26792]: TypeError: existingStyles.removeObject_ is not a function. (In 'existingStyles.removeObject_( style)', 'existingStyles.removeObject_' is undefined)
line: 41
sourceURL: ~/Library/Application Support/com.bohemiancoding.sketch3/Plugins/sync.sketchplugin/Contents/Sketch/script.cocoascript
column: 35
```

```
  function removeAllStyles() {
    var existingStyles = sharedStyles.objects();

    while (existingStyles.count() > 0) {
      style = existingStyles.objectAtIndex(0);
      [existingStyles removeObject:style];
    }
  }
```

**Comment by hashcc** [comment]
Caused by Sketch 39 API change
https://www.sketchapp.com/support/updates/sketch-39/

> Long deprecated Scripting-API methods have been removed from the code

**Comment by nolastan** [comment]
Thanks for the detailed report. I'll have to figure out what to replace this with.

I wish they would have thrown some deprecation warnings…

**Comment by nolastan** [comment]
I'm having trouble with this. I've posted to [teamsketch](https://teamsketch.slack.com) but I've never received help there before, so I'm not optimistic.

If anyone can help figure this out, here's the isolated code which can be run in script editor (`ctrl+shift+k`). You'll need to make a couple text styles first.

```
var doc = context.document;
var sharedStyles = doc.documentData().layerTextStyles()
var styles = sharedStyles.objects();
var style = styles.objectAtIndex(0);
// [styles removeObject:style]; ** fix this **
log(styles);
```

**Comment by patrickhill** [comment]
I've been trying to make this work but I have zero cocoascript knowledge so I'm not getting anywhere. I did find this gist which will dump the available properties and methods that might help. https://github.com/sketchplugins/plugin-requests/blob/master/Dump%20Selected%20Object.sketchplugin. I'd really like to see this plugin back in action so I'll keep messing with it but don't expect anything too helpful from me. ;)

**Comment by patrickhill** [comment]
// this seems to be working for me

var doc = context.document;
var sharedStyles = doc.documentData().layerTextStyles()
var styles = sharedStyles.objects();

[sharedStyles removeSharedObjectAtIndex:0]

log(styles);

**Comment by patrickhill** [comment]
I think I've fixed this issue but another has popped up with the setCharacterSpacing method. Looking into it now.

**Comment by patrickhill** [comment]
Just created a pull request with fixes that got the plugin working for me. Hopefully everything checks out and I didn't break anything!

**Comment by nolastan** [comment]
Thanks so much @patrickhill! Just made some comments on your PR https://github.com/nolastan/sync.sketchplugin/pull/22. Sorry the CharacterSpacing threw you off, https://github.com/nolastan/sync.sketchplugin/issues/20 is all about that.
