### ISSUE TITLE
Add support for paragraph spacing

### ISSUE THREAD

**Issue by patrickhill** [nolastan/sync.sketchplugin#23]
Neither the spreadsheet template or the plugin currently support paragraph spacing.

**Comment by username1290** [comment]
Hi, I think that's a Sketch bug

**Comment by patrickhill** [comment]
Doing some research. I found methods for setLineSpacing and setLineHeight for MSTextLayer. They can't both do the same thing so I'm hoping one of them controls paragraph spacing. Will test soon.

**Comment by nolastan** [comment]
Getting close. The following works if I have a text layer selected on the canvas. However, if I create a text layer dynamically (`[[MSTextLayer alloc] initWithFrame:nil];`), it doesn't have a `paragraphStyle` as part of `attributes`. So if we can just figure out how to add a `paragraphStyle` to `attributes` we should be set.

```
var layer = context.selection[0];
var paragraphStyle = layer.style().textStyle().attributes().NSParagraphStyle;
paragraphStyle.setParagraphSpacing(20);
```

**Comment by mathieudutour** [comment]
you should be able to do `layer.paragraphStyle().setParagraphSpacing(20)` directly

**Comment by nolastan** [comment]
@mathieudutour Thanks. I'd expect this to log `99`, but it logs `0`:

```
var textLayer = [[MSTextLayer alloc] initWithFrame:nil];
textLayer.paragraphStyle().setParagraphSpacing(99);
log(textLayer.paragraphStyle().paragraphSpacing())
```

**Comment by mathieudutour** [comment]
hum weird. Here is what I'm doing: https://github.com/mathieudutour/sketch-module-json-sync/blob/master/src/NS/spacing.js and it seems to work
