### ISSUE TITLE
can't send styles to sheet?

### ISSUE THREAD

**Issue by v3nt** [nolastan/sync.sketchplugin#9]
It just seems to get styles from the sheet and not send them from the sketch file?  Maybe different function to push or pull styles?

**Comment by nolastan** [comment]
Correct, this plugin doesn't export your styles from Sketch, it only imports it from Sheets.

**Comment by v3nt** [comment]
ok - i can't seem to find a plugin to export them - is there one?

**Comment by nolastan** [comment]
https://github.com/getflourish/Sketch-Style-Inventory is the closest I know of. Would be great if someone would build a bridge between the two plugins.
